function createMChart(d,b,a){$.get("/api?f=ggd&b="+d+"&m="+a+"&p="+b,function(a){createChart($.parseJSON(notIn(a)))})}function createMIChart(d,b){$.get("/api?f=ggd&m="+d+"&p="+b,function(a){createChart($.parseJSON(notIn(a)))})}function createPChart(d,b,a,e,f){$.get("/api?f=ggd&b="+d+"&m="+b+"&p="+a+"&pt="+e+"&tn="+f,function(a){createChart($.parseJSON(notIn(a)))})}function createPIChart(d,b,a,e){$.get("/api?f=ggd&m="+d+"&p="+b+"&pt="+a+"&tn="+e,function(a){createChart($.parseJSON(notIn(a)))})}
function createChart(d){Highcharts.setOptions({global:{useUTC:!1}});$("#chart-area").highcharts({chart:{type:"line",style:{fontFamily:"'Roboto', Arial, sans-serif"},marginTop:18},credits:{enabled:!1},legend:{enabled:!1},colors:["#393B42"],title:{text:"",style:{color:"#272727",fontSize:"12px",fontWeight:"bold"}},xAxis:{type:"datetime",dateTimeLabelFormats:{month:"%e. %b",year:"%b"},title:{text:""},tickPixelInterval:50},yAxis:{title:{text:""},labels:{formatter:function(){return 1<this.value?2==oddsType?
Highcharts.numberFormat(this.value,2):oneDecToML(this.value):""}},tickPixelInterval:50},tooltip:{formatter:function(){var b=this.series.xData.indexOf(this.x),a="";"undefined"!==typeof this.series.yData[b-1]&&(this.series.yData[b-1]<this.y?a='<span style="color: #4BCA02">\u25b2</span>':this.series.yData[b-1]>this.y&&(a='<span style="color: #E93524">\u25bc</span>'));b=2==oddsType?Highcharts.numberFormat(this.y,2):oneDecToML(this.y);return'<span style="color: #666; font-weight: bold; font-size: 11px">'+
Highcharts.dateFormat("%a %d. %b %H:%M",this.x)+"</span><br/>"+this.series.name+": <b>"+b+"</b>"+a+"<br/>"},style:{fontSize:"12px"}},plotOptions:{series:{step:"left",animation:!1},line:{lineWidth:1.75,marker:{enabled:!1,fillColor:"#666",radius:2},states:{hover:{lineWidth:1.75}},dataLabels:{shape:"callout",defer:!1,enabled:!0,formatter:function(){return 0==this.point.index||this.series.chart.series[0].points.length-1==this.point.index?2==oddsType?'<span style="margin-left: 4px; margin-right: 4px;">'+
Highcharts.numberFormat(this.y,2)+"</span>":'<span style="margin-left: 4px; margin-right: 4px;">'+oneDecToML(this.y)+"</span>":null},backgroundColor:"rgba(69, 69, 69, 0.8)",padding:3,style:{textShadow:0,fontSize:"11px",color:"#fff",fontWeight:"normal"},y:-8,overflow:"none",crop:!1,useHTML:!0}}},series:d})}
$(function(){function d(){var a=+new Date,e,f=b.length,g,c,k,h;for(e=0;e<f;e+=1)if(g=$(b[e]),c=g.data("sparkline"),c=c.split("; "),k=$.map(c[0].split(", "),parseFloat),h={},c[1]&&(h.type=c[1]),g.highcharts("SparkLine",{series:[{data:k,pointStart:1}],chart:h}),500<new Date-a){b.splice(0,e+1);setTimeout(d,0);break}}Highcharts.SparkLine=function(a,b){a=Highcharts.merge({chart:{renderTo:a.chart&&a.chart.renderTo||this,backgroundColor:null,borderWidth:0,type:"area",margin:[3,0,5,2],width:50,height:32,
className:"chart-spark",events:{click:function(a){var b=$.parseJSON($("#"+this.container.id).closest("td").attr("data-li")),c=$("#"+this.container.id).closest("tr").next("tr").find("th.oppcell").text(),c=$("#team-name").text()+' <span style="font-weight: normal;">(vs. '+c+") &#150; Mean odds";chartCC();createMIChart(b[0],b[1]);chartSC(c,a.clientX,a.clientY)}},style:{overflow:"visible"},skipClone:!0},colors:["#000"],title:{text:""},credits:{enabled:!1},xAxis:{labels:{enabled:!1},title:{text:null},
startOnTick:!1,endOnTick:!1,tickPositions:[]},yAxis:{endOnTick:!1,startOnTick:!1,labels:{enabled:!1},title:{text:null},tickPositions:[0]},legend:{enabled:!1},tooltip:{enabled:!1},plotOptions:{series:{threshold:null,animation:!1,lineWidth:.65,states:{hover:{enabled:!1}},shadow:!1,events:{click:function(a){var b=$.parseJSON($("#"+this.chart.container.id).closest("td").attr("data-li")),c=$("#"+this.chart.container.id).closest("tr").next("tr").find("th.oppcell").text(),c=$("#team-name").text()+' <span style="font-weight: normal;">(vs. '+
c+") &#150; Mean odds";chartCC();createMIChart(b[0],b[1]);chartSC(c,a.clientX,a.clientY)}},marker:{enabled:!1},fillColor:"#e9ebed"}}},a);return new Highcharts.Chart(a,b)};var b=$("td[data-sparkline]");d()});
